FROM node:18-alpine3.15

RUN mkdir server

WORKDIR /server

ENV MONGODB_URI=mongodb+srv://mybus:priuJr3FVQ96IcSB@cluster0.gn92lfx.mongodb.net/?retryWrites=true&w=majority

ENV PORT=9000

ENV HOST=localhost

COPY ./package.json yarn.lock ./

RUN yarn

COPY . .

EXPOSE 9000

CMD ["yarn","start"]