version: '3.7'
services:
  server:
    build: 
      dockerfile: dockerfile
      context: ./
  test:
    build:
      context: .
      dockerfile: dockerfile.test
    command:  npm run ci:e2e
    environment:
      - MONGODB_URI=mongodb+srv://mybus:priuJr3FVQ96IcSB@cluster0.gn92lfx.mongodb.net/?retryWrites=true&w=majority
      - PORT=9000
    ports:
      - 3000:3000