version: '3.7'

services:
  server:
    container_name: localserver
    build: 
      dockerfile: dockerfile.production
      context: ./
    ports:
      - 9000:9000
    environment:
      - MONGODB_URI=mongodb+srv://mybus:priuJr3FVQ96IcSB@cluster0.gn92lfx.mongodb.net/?retryWrites=true&w=majority
      - PORT=9000
      - HOST=localhost
    networks:
      - api
  test:
    container_name: server_test
    build:
      context: .
      dockerfile: dockerfile.local
    command:  npm test
    depends_on:
      - server
    environment:
      - MONGODB_URI=mongodb+srv://mybus:priuJr3FVQ96IcSB@cluster0.gn92lfx.mongodb.net/?retryWrites=true&w=majority
      - PORT=9000
      - HOST=localserver
    networks:
      - api
networks:
  api: 
    driver: bridge