version: '3.7'

services:
  web: {}
  server:
    container_name: localserver
    build: 
      dockerfile: dockerfile
      context: ./
    ports:
      - 9000:9000
    environment:
      - MONGODB_URI=mongodb+srv://mybus:priuJr3FVQ96IcSB@cluster0.gn92lfx.mongodb.net/?retryWrites=true&w=majority
      - PORT=9000
      - HOST=localhost
    networks:
      - api
  test:
    build:
      context: .
      dockerfile: dockerfile.test
    command:  npm test
    environment:
      - MONGODB_URI=mongodb+srv://mybus:priuJr3FVQ96IcSB@cluster0.gn92lfx.mongodb.net/?retryWrites=true&w=majority
      - PORT=9000
      - HOST=localserver
    networks:
      - api
networks:
  api: {}